apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics-svc
  namespace: exporter
  labels:
    app: postgres-metrics
spec:
  ports:
    - name: postgres-metrics-port
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-metrics
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-metrics
  namespace: exporter
  labels:
    name: database
    app: postgres-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-metrics
  template:
    metadata:
      labels:
        app: postgres-metrics
    spec:
      containers:
      - name: postgres-metrics
        image: postgres:14-alpine
        volumeMounts:
        - name: postgres-volume-mount
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: metrics
        - name: POSTGRES_PASSWORD
          value: metricspass
      restartPolicy: Always
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: postgres-metrics